title = "Website Name"
baseURL = 'https://example.org'
languageCode = 'en-us'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"
  x = "https://x.com/"
  yt = "https://youtube.com/"
  gh = "https://github.com/"

  #list items
  datesinlist = false
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true
  showx = true
  showyt = true
  showgh = true